BEGIN;
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (183, 12, 'Barclay issued a statement on the one-year anniversary of the October 7 attacks titled "Statement From Assembly Minority Leader Will Barclay on the Anniversary of Oct. 7." He mourned "the horrific events that took place in Israel one year ago today," expressed concern for hostages including Americans, and stated: "The cowardly acts of terror committed by Hamas on Oct. 7. have no place in this world, nor do the antisemitic uprisings we have seen so frequently in the aftermath of the attacks." He declared: "I proudly stand with the people of Israel and the Jewish community, and pray for their peace, safety and security during these unsettled times."', 'https://assembly.state.ny.us/mem/William-A-Barclay/story/112188', '2024-10-07');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (183, 5, 'Barclay co-sponsored Assembly Bill A4797 (2025), the "Stop Anti-Semitism on College Campuses Act," which would ensure no state aid is granted to any college or university that authorizes, facilitates, provides funding for, or otherwise supports any event promoting antisemitism on campus. He also co-sponsored A2376 (2025), the "Dismantling Student Antisemitism Act" (DSA Act), requiring mandatory sensitivity training on antisemitism and reporting requirements.', 'https://www.nysenate.gov/legislation/bills/2025/A4797', '2025-02-06');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (184, 5, 'Angelino co-sponsored three antisemitism protection bills in the 2025-2026 session: (1) A4797, the "Stop Anti-Semitism on College Campuses Act," ensuring no state aid to institutions supporting events promoting antisemitism; (2) A4772, the "Combating Campus Antisemitism Act," prohibiting tuition assistance awards to students who knowingly promote antisemitism likely to incite lawless action; and (3) A2376, the "Dismantling Student Antisemitism Act," requiring mandatory sensitivity training on antisemitism at CUNY, SUNY, and accredited institutions.', 'https://www.nysenate.gov/legislation/bills/2025/A4797', '2025-02-06');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (185, 5, 'Miller co-sponsored Assembly Bill A4797 (2025), the "Stop Anti-Semitism on College Campuses Act," which would bar state aid to colleges or universities supporting events promoting antisemitism. He also co-sponsored A4772 (2025), the "Combating Campus Antisemitism Act," prohibiting tuition assistance to students who knowingly promote antisemitism in a manner likely to incite lawless action.', 'https://www.nysenate.gov/legislation/bills/2025/A4797', '2025-02-06');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (187, 5, 'Friend co-sponsored Assembly Bill A4797 (2025), the "Stop Anti-Semitism on College Campuses Act," which would bar state aid to colleges or universities supporting events promoting antisemitism. He also co-sponsored A4772 (2025), the "Combating Campus Antisemitism Act," prohibiting tuition assistance to students who knowingly promote antisemitism in a manner likely to incite lawless action.', 'https://www.nysenate.gov/legislation/bills/2025/A4797', '2025-02-06');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (189, 12, 'Lemondes issued a statement commending President Trump for the Gaza ceasefire and release of 20 Israeli hostages. He stated: "The return of these brave men and women to their families is a moving sight, and I thank President Trump and his leadership for delivering this powerful victory for humanity and for our ally, Israel. Peace happens through strength, and with the help of our allies in the region and the president''s resolve, these hostages are now home, and a ceasefire is secured. This is what effective, no-nonsense diplomacy achieves."', 'https://assembly.state.ny.us/mem/John-Lemondes/story/115566', '2025-10-15');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (189, 6, 'Lemondes praised the ceasefire outcome as "a powerful victory for humanity and for our ally, Israel," explicitly framing the U.S.-Israel relationship as an alliance and stating "Peace happens through strength," indicating support for a strong U.S.-Israel security relationship.', 'https://assembly.state.ny.us/mem/John-Lemondes/story/115566', '2025-10-15');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (189, 5, 'Lemondes co-sponsored Assembly Bill A4797 (2025), the "Stop Anti-Semitism on College Campuses Act," which would bar state aid to colleges or universities supporting events promoting antisemitism. He also co-sponsored A4772 (2025), the "Combating Campus Antisemitism Act," prohibiting tuition assistance to students who knowingly promote antisemitism in a manner likely to incite lawless action.', 'https://www.nysenate.gov/legislation/bills/2025/A4797', '2025-02-06');
COMMIT;
