-- Update CHECK constraint to allow city_council chamber
ALTER TABLE legislators DROP CONSTRAINT legislators_chamber_check;
ALTER TABLE legislators ADD CONSTRAINT legislators_chamber_check CHECK (chamber IN ('senate', 'assembly', 'city_council'));

-- Insert all 51 NYC City Council members
-- Party: 46 Democrats, 5 Republicans
-- Email pattern: District{N}@council.nyc.gov

INSERT INTO legislators (chamber, district, name, party, phone_albany, phone_district, email) VALUES
('city_council', 1, 'Christopher Marte', 'Democratic', NULL, '212-587-3159', 'District1@council.nyc.gov'),
('city_council', 2, 'Harvey Epstein', 'Democratic', NULL, NULL, 'District2@council.nyc.gov'),
('city_council', 3, 'Vacant', NULL, NULL, NULL, 'District3@council.nyc.gov'),
('city_council', 4, 'Virginia Maloney', 'Democratic', NULL, NULL, 'District4@council.nyc.gov'),
('city_council', 5, 'Julie Menin', 'Democratic', NULL, NULL, 'District5@council.nyc.gov'),
('city_council', 6, 'Gale A. Brewer', 'Democratic', NULL, NULL, 'District6@council.nyc.gov'),
('city_council', 7, 'Shaun Abreu', 'Democratic', NULL, NULL, 'District7@council.nyc.gov'),
('city_council', 8, 'Elsie Encarnacion', 'Democratic', NULL, NULL, 'District8@council.nyc.gov'),
('city_council', 9, 'Yusef Salaam', 'Democratic', NULL, NULL, 'District9@council.nyc.gov'),
('city_council', 10, 'Carmen De La Rosa', 'Democratic', NULL, NULL, 'District10@council.nyc.gov'),
('city_council', 11, 'Eric Dinowitz', 'Democratic', NULL, NULL, 'District11@council.nyc.gov'),
('city_council', 12, 'Kevin C. Riley', 'Democratic', NULL, NULL, 'District12@council.nyc.gov'),
('city_council', 13, 'Shirley Aldebol', 'Democratic', NULL, NULL, 'District13@council.nyc.gov'),
('city_council', 14, 'Pierina Ana Sanchez', 'Democratic', NULL, NULL, 'District14@council.nyc.gov'),
('city_council', 15, 'Oswald Feliz', 'Democratic', NULL, NULL, 'District15@council.nyc.gov'),
('city_council', 16, 'Althea Stevens', 'Democratic', NULL, NULL, 'District16@council.nyc.gov'),
('city_council', 17, 'Justin Sanchez', 'Democratic', NULL, NULL, 'District17@council.nyc.gov'),
('city_council', 18, 'Amanda Farias', 'Democratic', NULL, NULL, 'District18@council.nyc.gov'),
('city_council', 19, 'Vickie Paladino', 'Republican', NULL, NULL, 'District19@council.nyc.gov'),
('city_council', 20, 'Sandra Ung', 'Democratic', NULL, NULL, 'District20@council.nyc.gov'),
('city_council', 21, 'Shanel Thomas-Henry', 'Democratic', NULL, NULL, 'District21@council.nyc.gov'),
('city_council', 22, 'Tiffany Caban', 'Democratic', NULL, NULL, 'District22@council.nyc.gov'),
('city_council', 23, 'Linda Lee', 'Democratic', NULL, NULL, 'District23@council.nyc.gov'),
('city_council', 24, 'James F. Gennaro', 'Democratic', NULL, NULL, 'District24@council.nyc.gov'),
('city_council', 25, 'Shekar Krishnan', 'Democratic', NULL, NULL, 'District25@council.nyc.gov'),
('city_council', 26, 'Julie Won', 'Democratic', NULL, NULL, 'District26@council.nyc.gov'),
('city_council', 27, 'Nantasha Williams', 'Democratic', NULL, NULL, 'District27@council.nyc.gov'),
('city_council', 28, 'Ty Hankerson', 'Democratic', NULL, NULL, 'District28@council.nyc.gov'),
('city_council', 29, 'Lynn Schulman', 'Democratic', NULL, NULL, 'District29@council.nyc.gov'),
('city_council', 30, 'Phil Wong', 'Democratic', NULL, NULL, 'District30@council.nyc.gov'),
('city_council', 31, 'Selvena N. Brooks-Powers', 'Democratic', NULL, NULL, 'District31@council.nyc.gov'),
('city_council', 32, 'Joann Ariola', 'Republican', NULL, NULL, 'District32@council.nyc.gov'),
('city_council', 33, 'Lincoln Restler', 'Democratic', NULL, NULL, 'District33@council.nyc.gov'),
('city_council', 34, 'Jennifer Gutierrez', 'Democratic', NULL, NULL, 'District34@council.nyc.gov'),
('city_council', 35, 'Crystal Hudson', 'Democratic', NULL, NULL, 'District35@council.nyc.gov'),
('city_council', 36, 'Chi Osse', 'Democratic', NULL, NULL, 'District36@council.nyc.gov'),
('city_council', 37, 'Sandy Nurse', 'Democratic', NULL, NULL, 'District37@council.nyc.gov'),
('city_council', 38, 'Alexa Aviles', 'Democratic', NULL, NULL, 'District38@council.nyc.gov'),
('city_council', 39, 'Shahana Hanif', 'Democratic', NULL, NULL, 'District39@council.nyc.gov'),
('city_council', 40, 'Rita Joseph', 'Democratic', NULL, NULL, 'District40@council.nyc.gov'),
('city_council', 41, 'Darlene Mealy', 'Democratic', NULL, NULL, 'District41@council.nyc.gov'),
('city_council', 42, 'Chris Banks', 'Democratic', NULL, NULL, 'District42@council.nyc.gov'),
('city_council', 43, 'Susan Zhuang', 'Democratic', NULL, NULL, 'District43@council.nyc.gov'),
('city_council', 44, 'Simcha Felder', 'Democratic', NULL, NULL, 'District44@council.nyc.gov'),
('city_council', 45, 'Farah N. Louis', 'Democratic', NULL, NULL, 'District45@council.nyc.gov'),
('city_council', 46, 'Mercedes Narcisse', 'Democratic', NULL, NULL, 'District46@council.nyc.gov'),
('city_council', 47, 'Kayla Santosuosso', 'Democratic', NULL, NULL, 'District47@council.nyc.gov'),
('city_council', 48, 'Inna Vernikov', 'Republican', NULL, NULL, 'District48@council.nyc.gov'),
('city_council', 49, 'Kamillah Hanks', 'Democratic', NULL, NULL, 'District49@council.nyc.gov'),
('city_council', 50, 'David Carr', 'Republican', NULL, NULL, 'District50@council.nyc.gov'),
('city_council', 51, 'Frank Morano', 'Republican', NULL, NULL, 'District51@council.nyc.gov');
