BEGIN;
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 9, 'Mamdani appeared on ABC''s "The View" and called Israel''s war in Gaza a "genocide," earning audience applause. He stated: "my belief in a universality in international law is also the same set of beliefs that led me to describe what''s happening in Gaza as a genocide"', 'https://www.timesofisrael.com/mamdani-appearing-on-the-view-earns-applause-for-calling-gaza-war-a-genocide/', '2025-10-01');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 9, 'Mamdani used the word "genocide" to describe Israeli actions in Gaza just days after the Oct 7 attack and before Israel had begun ground operations. On Oct 13, 2023, after his arrest at a protest, he stated: "I plan to continue to speak out against this impending genocide of Palestinians"', 'https://qns.com/2023/10/mamdani-arrested-protest-brooklyn/', '2023-10-13');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 9, 'Mamdani staged a five-day hunger strike outside the White House in November 2023 calling for a ceasefire, stating: "The United States is not simply a witness to this genocide. It''s an actor in this genocide"', 'https://time.com/6340016/lawmakers-activists-ceasefire-gaza-hunger-strike/', '2023-11-27');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 9, 'Mamdani told President Trump at a meeting that Israel is "committing genocide" in Gaza', 'https://www.aljazeera.com/video/newsfeed/2025/11/22/mamdani-says-israel-is-committing-genocide-in-gaza-at-trump-meeting', '2025-11-22');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 10, 'Mamdani posted on X/Twitter on Oct 8, 2023, the day after the Hamas attack, stating: "the path toward a just and lasting peace can only begin by ending the occupation and dismantling apartheid"', 'https://www.jpost.com/diaspora/antisemitism/article-859044', '2023-10-08');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 10, 'Mamdani wrote on the second anniversary of Oct 7: "The occupation and apartheid must end," and was described by The View co-host Sara Haines as having "made inflammatory statements, like calling Israel an apartheid state"', 'https://www.cbsnews.com/newyork/news/nyc-mayors-race-zohran-mamdani-october-7-statement-israel/', '2025-10-07');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 11, 'Mamdani was arrested on Oct 13, 2023, outside Senate Majority Leader Chuck Schumer''s Brooklyn home during a Jewish Voice for Peace protest calling for a ceasefire in Gaza, just six days after the Oct 7 attack', 'https://qns.com/2023/10/mamdani-arrested-protest-brooklyn/', '2023-10-13');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 11, 'Mamdani staged a five-day hunger strike outside the White House in late November 2023 to pressure President Biden to support a permanent ceasefire in Gaza, tweeting: "Four days of sitting outside of the White House in the cold, calling on Pres. Biden to support a permanent ceasefire"', 'https://x.com/ZohranKMamdani/status/1730428978677088296', '2023-11-30');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 11, 'Mamdani participated in the Jewish Voice for Peace Grand Central Station sit-in on Oct 27, 2023, which shut down NYC''s main transportation hub during rush hour to demand a ceasefire, stating: "a call to value Palestinian lives and call for a ceasefire is the majority position in this country"', 'https://www.democracynow.org/2023/10/30/grand_central_protest', '2023-10-27');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 13, 'Mamdani''s Oct 8, 2023 statement mourned "the hundreds of people killed across Israel and Palestine" but immediately pivoted to blaming Netanyahu''s "declaration of war" and Israel cutting electricity to Gaza, concluding the path to peace requires "ending the occupation and dismantling apartheid" — criticized for devoting two sentences to Hamas atrocities and three paragraphs to condemning Israel', 'https://www.jpost.com/diaspora/antisemitism/article-859044', '2023-10-08');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 13, 'Mamdani''s Oct 7, 2025 anniversary statement was deemed "shameful" by Israel''s Foreign Ministry, which accused him of acting as "a mouthpiece for Hamas propaganda — spreading Hamas''s fake genocide campaign." While he called Oct 7 a "horrific war crime," the bulk of his statement focused on condemning Israel''s response as genocide', 'https://www.cbsnews.com/newyork/news/nyc-mayors-race-zohran-mamdani-october-7-statement-israel/', '2025-10-07');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 13, 'Mamdani refused to condemn "globalize the intifada" chants, saying on NBC''s Meet the Press on June 19, 2025 that the phrase captures "a desperate desire for equality and equal rights" and citing the U.S. Holocaust Museum''s use of "intifada" to describe the Warsaw Ghetto Uprising, rather than condemning the slogan', 'https://www.nbcnews.com/news/us-news/nyc-mayoral-candidate-zohran-mamdani-draws-criticism-intifada-remarks-rcna213967', '2025-06-19');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 15, 'Mamdani was arrested for disorderly conduct on Oct 13, 2023, while participating in a Jewish Voice for Peace protest outside Chuck Schumer''s Brooklyn home, blocking traffic to demand a ceasefire in Gaza just six days after the Hamas attack', 'https://qns.com/2023/10/mamdani-arrested-protest-brooklyn/', '2023-10-13');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 15, 'Mamdani participated in the Grand Central Station sit-in on Oct 27, 2023, organized by Jewish Voice for Peace, which shut down the terminal during rush hour with nearly 400 arrests to demand a Gaza ceasefire', 'https://www.democracynow.org/2023/10/30/grand_central_protest', '2023-10-27');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 15, 'Mamdani spoke at a May 11, 2021, pro-Palestinian rally where he declared "I am a proud Socialist and I''m a proud member of the New York City DSA," led chants of "BDS," and stated "Anti-Zionism is not antisemitism, and in the anti-Zionist movement that I believe in and belong to, there is no room for antisemitism"', 'https://www.timesofisrael.com/nyc-mayoral-candidate-mamdani-declared-hes-anti-zionist-at-2021-protest-video-shows/', '2021-05-11');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 15, 'Mamdani staged a five-day hunger strike outside the White House in November 2023, joining four other state lawmakers to demand President Biden support a permanent ceasefire, calling the U.S. "an actor in this genocide"', 'https://time.com/6340016/lawmakers-activists-ceasefire-gaza-hunger-strike/', '2023-11-27');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 8, 'Mamdani sponsored the "Not on Our Dime: Ending New York Funding of Israeli Settler Violence Act" (A6101) in the NY Assembly in May 2023, which would prohibit New York not-for-profit corporations from supporting Israeli settlement activity and impose fines of at least $1 million for violations', 'https://www.nysenate.gov/legislation/bills/2025/A6101', '2023-05-01');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 3, 'Mamdani was the lead sponsor of A6101, the "Not on Our Dime" bill, which targeted New York nonprofits funding Israeli settlement activity in the West Bank, co-sponsored by Assemblymembers Shrestha, Forrest, Mitaynes, and Gallagher', 'https://www.timesofisrael.com/as-ny-assemblyman-mamdani-pushed-bill-barring-nonprofits-from-supporting-israeli-settlement-activity/', '2023-05-01');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 13, 'Mamdani revoked the IHRA Working Definition of Antisemitism executive order on his first day as NYC mayor (Jan 1, 2026), overturning Adams-era adoption of the definition that classifies some criticism of Israel as antisemitic. Israel''s Foreign Ministry accused him of "fueling antisemitism"', 'https://www.jta.org/2026/01/02/ny/mamdanis-first-act-revoking-eric-adams-executive-orders-including-on-israel-antisemitism-and-bds', '2026-01-01');
INSERT INTO person_criteria (person_id, criterion_id, evidence, source_url, source_date)
VALUES (293, 8, 'Mamdani revoked the anti-BDS executive order on his first day as NYC mayor (Jan 1, 2026), rescinding the Adams-era directive that barred city employees and agencies from boycotting or divesting from Israel, as a supporter of the BDS movement', 'https://www.cnn.com/2026/01/02/politics/zohran-mamdani-housing-israel-executive-orders', '2026-01-01');

-- Recompute stance: all anti, score will be very negative
INSERT INTO positions (person_id, topic_id, stance, confidence, rationale, assessment_type)
VALUES (293, 1, 'strongly_oppose', 'inferred', 'Anti-Israel: Sponsored anti-settlement legislation, supports conditioning US aid, used "genocide" and "apartheid" labels, called for unconditional ceasefire, equivocated on Oct 7, attended anti-Israel protests/rallies, revoked IHRA and anti-BDS executive orders as NYC Mayor. Score: -46 (21 evidence items).', 'ai');
COMMIT;
